### ISSUE TITLE
[CICD] Increment Lambda Versions in CodeDeploy AppSpec Config

### ISSUE THREAD

**Issue by jwallace145** [jwallace145/walterai-backend#1]
To update the WalterAIBackend Lambda source code, the contents of this repo are zipped and uploaded to S3 and then the function is updated to use the new source code.

However, CodeDeploy orchestrates shifting the traffic from the current version to the target version via the `appspec.yml`, e.g.: 

```yaml
version: 0.0

Resources:
  - MyFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "WalterAIBackend-dev"
        Alias: "WalterAIBackend-dev"
        CurrentVersion: "1"
        TargetVersion: "2"
```

This file needs to be generated with each deployment to bump the versions so CodeDeploy knows which version to shift traffic to. 

To solve this, write a simple Python script (with Jinja perhaps) that gets the current Lambda version and the latest version and generates a corresponding `appspec.yml` so deployments work seamlessly.
